<?php

class ARMS {
	private static $initiated = false;

	public static function init() {
		if ( ! self::$initiated ) {
			self::init_hooks();
		}
	}

	/**
	 * Initializes WordPress hooks
	 */
	private static function init_hooks() {
		self::$initiated = true;

		self::register_post_type();
		//add_filter( 'rwmb_meta_boxes', array( 'ARMS', 'arms_get_meta_box' ) );
		add_filter( 'enter_title_here', array( 'ARMS', 'arms_change_title_text' ) );

		add_action( 'admin_enqueue_scripts', array( 'ARMS', 'add_admin_scripts' ), 10, 1 );
	}

	public static function arms_change_title_text( $title ) {
		 $screen = get_current_screen();

		if ( 'pet' == $screen->post_type ) {
			 $title = 'Enter pet name';
		}

		 return $title;
	}

	public static function add_admin_scripts( $hook ) {

		global $post;

		if ( $hook == 'post-new.php' || $hook == 'post.php' ) {
			if ( 'pet' === $post->post_type ) {
				wp_enqueue_script( 'arms_admin_js', plugin_dir_url( __FILE__ ) . '/js/arms-admin.js' );
			}
		}
	}

	public static function register_post_type() {
		$labels = array(
			'name'               => _x( 'Pets', 'post type general name', 'your-plugin-textdomain' ),
			'singular_name'      => _x( 'Pet', 'post type singular name', 'your-plugin-textdomain' ),
			'menu_name'          => _x( 'Pets', 'admin menu', 'your-plugin-textdomain' ),
			'name_admin_bar'     => _x( 'Pet', 'add new on admin bar', 'your-plugin-textdomain' ),
			'add_new'            => _x( 'Add New', 'pet', 'your-plugin-textdomain' ),
			'add_new_item'       => __( 'Add New Pet', 'your-plugin-textdomain' ),
			'new_item'           => __( 'New Pet', 'your-plugin-textdomain' ),
			'edit_item'          => __( 'Edit Pet', 'your-plugin-textdomain' ),
			'view_item'          => __( 'View Pet', 'your-plugin-textdomain' ),
			'all_items'          => __( 'All Pets', 'your-plugin-textdomain' ),
			'search_items'       => __( 'Search Pets', 'your-plugin-textdomain' ),
			'parent_item_colon'  => __( 'Parent Pets:', 'your-plugin-textdomain' ),
			'not_found'          => __( 'No pets found.', 'your-plugin-textdomain' ),
			'not_found_in_trash' => __( 'No pets found in Trash.', 'your-plugin-textdomain' ),
		);

		$args = array(
			'labels'             => $labels,
			'description'        => __( 'Description.', 'your-plugin-textdomain' ),
			'public'             => true,
			'publicly_queryable' => true,
			'show_ui'            => true,
			'show_in_menu'       => true,
			'query_var'          => true,
			/*'rewrite'            => array( 'slug' => 'pet' ),*/
			'capability_type'    => 'post',
			'has_archive'        => true,
			'hierarchical'       => false,
			'menu_position'      => null,
			'menu_icon'          => 'dashicons-heart',
			'supports'           => array( 'title', 'editor', 'thumbnail' ),
		);

		register_post_type( 'pet', $args );
	}

	public static function arms_get_meta_box( $meta_boxes ) {
		$cat_breed_array = array(
			'Abyssinian',
			'American Curl',
			'American Shorthair',
			'American Wirehair',
			'Applehead Siamese',
			'Balinese',
			'Bengal',
			'Birman',
			'Bobtail',
			'Bombay',
			'British Shorthair',
			'Burmese',
			'Burmilla',
			'Calico',
			'Canadian Hairless',
			'Chartreux',
			'Chausie',
			'Chinchilla',
			'Cornish Rex',
			'Cymric',
			'Devon Rex',
			'Dilute Calico',
			'Dilute Tortoiseshell',
			'Domestic Long Hair',
			'Domestic Long Hair - buff',
			'Domestic Long Hair - buff and white',
			'Domestic Long Hair - gray and white',
			'Domestic Long Hair - orange',
			'Domestic Long Hair - orange and white',
			'Domestic Long Hair-black',
			'Domestic Long Hair-black and white',
			'Domestic Long Hair-gray',
			'Domestic Long Hair-white',
			'Domestic Medium Hair',
			'Domestic Medium Hair - buff',
			'Domestic Medium Hair - buff and white',
			'Domestic Medium Hair - gray and white',
			'Domestic Medium Hair - orange and white',
			'Domestic Medium Hair-black',
			'Domestic Medium Hair-black and white',
			'Domestic Medium Hair-gray',
			'Domestic Medium Hair-orange',
			'Domestic Medium Hair-white',
			'Domestic Short Hair',
			'Domestic Short Hair - buff',
			'Domestic Short Hair - buff and white',
			'Domestic Short Hair - gray and white',
			'Domestic Short Hair - orange and white',
			'Domestic Short Hair-black',
			'Domestic Short Hair-black and white',
			'Domestic Short Hair-gray',
			'Domestic Short Hair-mitted',
			'Domestic Short Hair-orange',
			'Domestic Short Hair-white',
			'Egyptian Mau',
			'Exotic Shorthair',
			'Extra-Toes Cat (Hemingway Polydactyl)',
			'Havana',
			'Himalayan',
			'Japanese Bobtail',
			'Javanese',
			'Korat',
			'LaPerm',
			'Maine Coon',
			'Manx',
			'Munchkin',
			'Nebelung',
			'Norwegian Forest Cat',
			'Ocicat',
			'Oriental Long Hair',
			'Oriental Short Hair',
			'Oriental Tabby',
			'Persian',
			'Pixie-Bob',
			'Ragamuffin',
			'Ragdoll',
			'Russian Blue',
			'Scottish Fold',
			'Selkirk Rex',
			'Siamese',
			'Siberian',
			'Singapura',
			'Snowshoe',
			'Somali',
			'Sphynx (hairless cat)',
			'Tabby',
			'Tabby - black',
			'Tabby - Brown',
			'Tabby - buff',
			'Tabby - Grey',
			'Tabby - Orange',
			'Tabby - white',
			'Tiger',
			'Tonkinese',
			'Torbie',
			'Tortoiseshell',
			'Turkish Angora',
			'Turkish Van',
			'Tuxedo',
		);

		$dog_breed_array = array(
			'Affenpinscher',
			'Afghan Hound',
			'Airedale Terrier',
			'Akbash',
			'Akita',
			'Alaskan Malamute',
			'American Bulldog',
			'American Eskimo Dog',
			'American Staffordshire Terrier',
			'American Water Spaniel',
			'Anatolian Shepherd',
			'Appenzell Mountain Dog',
			'Australian Cattle Dog/Blue Heeler',
			'Australian Kelpie',
			'Australian Shepherd',
			'Australian Terrier',
			'Basenji',
			'Basset Hound',
			'Beagle',
			'Bearded Collie',
			'Beauceron',
			'Bedlington Terrier',
			'Belgian Shepherd Dog Sheepdog',
			'Belgian Shepherd Laekenois',
			'Belgian Shepherd Malinois',
			'Belgian Shepherd Tervuren',
			'Bernese Mountain Dog',
			'Bichon Frise',
			'Black and Tan Coonhound',
			'Black Labrador Retriever',
			'Black Mouth Cur',
			'Black Russian Terrier',
			'Bloodhound',
			'Blue Lacy',
			'Bluetick Coonhound',
			'Border Collie',
			'Border Terrier',
			'Borzoi',
			'Boston Terrier',
			'Bouvier des Flanders',
			'Boxer',
			'Boykin Spaniel',
			'Briard',
			'Brittany Spaniel',
			'Brussels Griffon',
			'Bull Terrier',
			'Bullmastiff',
			'Cairn Terrier',
			'Canaan Dog',
			'Cane Corso Mastiff',
			'Carolina Dog',
			'Catahoula Leopard Dog',
			'Cattle Dog',
			'Caucasian Sheepdog (Caucasian Ovtcharka)',
			'Cavalier King Charles Spaniel',
			'Chesapeake Bay Retriever',
			'Chihuahua',
			'Chinese Crested Dog',
			'Chinese Foo Dog',
			'Chinook',
			'Chocolate Labrador Retriever',
			'Chow Chow',
			'Cirneco dell\'Etna',
			'Clumber Spaniel',
			'Cockapoo',
			'Cocker Spaniel',
			'Collie',
			'Coonhound',
			'Corgi',
			'Coton de Tulear',
			'Curly-Coated Retriever',
			'Dachshund',
			'Dalmatian',
			'Dandi Dinmont Terrier',
			'Doberman Pinscher',
			'Dogo Argentino',
			'Dogue de Bordeaux',
			'Dutch Shepherd',
			'English Bulldog',
			'English Cocker Spaniel',
			'English Coonhound',
			'English Pointer',
			'English Setter',
			'English Shepherd',
			'English Springer Spaniel',
			'English Toy Spaniel',
			'Entlebucher',
			'Eskimo Dog',
			'Feist',
			'Field Spaniel',
			'Fila Brasileiro',
			'Finnish Lapphund',
			'Finnish Spitz',
			'Flat-coated Retriever',
			'Fox Terrier',
			'Foxhound',
			'French Bulldog',
			'Galgo Spanish Greyhound',
			'German Pinscher',
			'German Shepherd Dog',
			'German Shorthaired Pointer',
			'German Spitz',
			'German Wirehaired Pointer',
			'Giant Schnauzer',
			'Glen of Imaal Terrier',
			'Golden Retriever',
			'Gordon Setter',
			'Great Dane',
			'Great Pyrenees',
			'Greater Swiss Mountain Dog',
			'Greyhound',
			'Harrier',
			'Havanese',
			'Hound',
			'Hovawart',
			'Husky',
			'Ibizan Hound',
			'Illyrian Sheepdog',
			'Irish Setter',
			'Irish Terrier',
			'Irish Water Spaniel',
			'Irish Wolfhound',
			'Italian Greyhound',
			'Italian Spinone',
			'Jack Russell Terrier',
			'Jack Russell Terrier (Parson Russell Terrier)',
			'Japanese Chin',
			'Jindo',
			'Kai Dog',
			'Karelian Bear Dog',
			'Keeshond',
			'Kerry Blue Terrier',
			'Kishu',
			'Klee Kai',
			'Komondor',
			'Kuvasz',
			'Kyi Leo',
			'Labrador Retriever',
			'Lancashire Heeler',
			'Lancashire Heeler',
			'Leonberger',
			'Lhasa Apso',
			'Lowchen',
			'Maltese',
			'Manchester Terrier',
			'Maremma Sheepdog',
			'Mastiff',
			'McNab',
			'Miniature Pinscher',
			'Mountain Cur',
			'Mountain Dog',
			'Munsterlander',
			'Neapolitan Mastiff',
			'New Guinea Singing Dog',
			'Newfoundland Dog',
			'Norfolk Terrier',
			'Norwegian Buhund',
			'Norwegian Elkhound',
			'Norwegian Lundehund',
			'Norwich Terrier',
			'Nova Scotia Duck-Tolling Retriever',
			'Old English Sheepdog',
			'Otterhound',
			'Papillon',
			'Patterdale Terrier (Fell Terrier)',
			'Pekingese',
			'Peruvian Inca Orchid',
			'Petit Basset Griffon Vendeen',
			'Pharaoh Hound',
			'Pit Bull Terrier',
			'Plott Hound',
			'Podengo Portugueso',
			'Pointer',
			'Polish Lowland Sheepdog',
			'Pomeranian',
			'Poodle',
			'Portuguese Water Dog',
			'Presa Canario',
			'Pug',
			'Puli',
			'Pumi',
			'Rat Terrier',
			'Redbone Coonhound',
			'Retriever',
			'Rhodesian Ridgeback',
			'Rottweiler',
			'Saint Bernard',
			'Saluki',
			'Samoyed',
			'Schipperke',
			'Schnauzer',
			'Scottish Deerhound',
			'Scottish Terrier Scottie',
			'Sealyham Terrier',
			'Setter',
			'Shar Pei',
			'Sheep Dog',
			'Shepherd',
			'Shetland Sheepdog Sheltie',
			'Shiba Inu',
			'Shih Tzu',
			'Siberian Husky',
			'Silky Terrier',
			'Skye Terrier',
			'Sloughi',
			'Smooth Fox Terrier',
			'South Russian Ovtcharka',
			'Spaniel',
			'Spitz',
			'Staffordshire Bull Terrier',
			'Standard Poodle',
			'Sussex Spaniel',
			'Swedish Vallhund',
			'Terrier',
			'Thai Ridgeback',
			'Tibetan Mastiff',
			'Tibetan Spaniel',
			'Tibetan Terrier',
			'Tosa Inu',
			'Toy Fox Terrier',
			'Treeing Walker Coonhound',
			'Vizsla',
			'Weimaraner',
			'Welsh Corgi',
			'Welsh Springer Spaniel',
			'Welsh Terrier',
			'West Highland White Terrier Westie',
			'Wheaten Terrier',
			'Whippet',
			'White German Shepherd',
			'Wire-haired Pointing Griffon',
			'Wirehaired Terrier',
			'Xoloitzcuintle/Mexican Hairless',
			'Yellow Labrador Retriever',
			'Yorkshire Terrier Yorkie',
		);
		$prefix = 'arms-';

		$meta_boxes[] = array(
			'id' => 'untitled',
			'title' => esc_html__( 'Pet Information', 'arms' ),
			'post_types' => array( 'pet' ),
			'context' => 'normal',
			'priority' => 'default',
			'autosave' => false,
			'fields' => array(
				array(
					'id' => 'pet_id',
					'type' => 'number',
					'name' => 'Legacy Pet ID',
				),
				array(
					'id' => 'tagNum',
					'type' => 'text',
					'name' => 'Tag Number',
				),
				array(
					'id' => 'pet_status',
					'type' => 'select',
					'name' => 'Primary Pet Status',
					'placeholder' => 'Select a status',
					'options' => array(
						'c' => 'Created',
						'q' => 'Quarantined',
						'v' => 'Available',
						's' => 'Sidelined',
						'a' => 'Adopted',
						'd' => 'Deceased',
						'r' => 'Other',
						'p' => 'Adoption Pending',
						't' => 'Transferred Out of KAR',
						'u' => 'Returned to Relinquisher',
					),
				),
				array(
					'id' => 'pet_status2',
					'type' => 'select',
					'name' => 'Secondary Pet Status',
					'options' => array(
						'n' => 'None',
						'e' => 'Euthanized',
						'm' => 'Medical',
						'a' => 'Application Screening',
						'i' => 'Incomplete/Missing Info',
						'o' => 'Other',
					),
				),
				array(
					'id' => 'adoptFee',
					'type' => 'number',
					'name' => 'Adoption Fee',
				),
				array(
					'id' => 'pet_type',
					'type' => 'select',
					'name' => 'Pet Type',
					'options' => array(
						'c' => 'Cat',
						'd' => 'Dog',
					),
				),
				array(
					'id' => 'pet_mom',
					'type' => 'user',
					'name' => 'Pet Parent (Primary)',
					'field_type' => 'select_advanced',
				),
				array(
					'id' => 'pet_mom2',
					'type' => 'user',
					'name' => 'Pet Parent (Secondary)',
					'field_type' => 'select_advanced',
				),
				array(
					'id' => 'pet_sex',
					'type' => 'radio',
					'name' => 'Pet Sex',
					'options' => array(
						'm' => 'Male',
						'f' => 'Female',
					),
				),
				array(
					'id' => 'pf_age',
					'type' => 'radio',
					'name' => 'Petfinder Age',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'pet_DOB',
					'type' => 'date',
					'name' => 'Date of Birth',
				),
				array(
					'id' => 'declawed',
					'type' => 'radio',
					'name' => 'Declawed',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'rabiesVac',
					'type' => 'radio',
					'name' => 'Rabies Vacination',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'microchipped',
					'type' => 'radio',
					'name' => 'Microchipped',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'microchipBrand',
					'type' => 'text',
					'name' => 'Microchip Brand',
				),
				array(
					'id' => 'microchipID',
					'type' => 'text',
					'name' => 'Microchip ID',
				),
				array(
					'id' => 'primaryBreed',
					'type' => 'select',
					'name' => 'primaryBreed',
					'options' => $dog_breed_array,
				),
				array(
					'id' => 'secondaryBreed',
					'type' => 'select',
					'name' => 'secondaryBreed',
					'options' => $dog_breed_array,
				),
				array(
					'id' => 'pet_mixed',
					'type' => 'radio',
					'name' => 'pet_mixed',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'pet_size',
					'type' => 'radio',
					'name' => 'pet_size',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'hasShots',
					'type' => 'radio',
					'name' => 'hasShots',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'altered',
					'type' => 'radio',
					'name' => 'Spayed/Neutered',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'noCats',
					'type' => 'radio',
					'name' => 'No Cats',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'noDogs',
					'type' => 'radio',
					'name' => 'No Dogs',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'noKids',
					'type' => 'radio',
					'name' => 'No Kids',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'housebroken',
					'type' => 'radio',
					'name' => 'Housebroken',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'spec_need',
					'type' => 'radio',
					'name' => 'Special Needs',
					'options' => array(
						'y' => 'Yes',
						'n' => 'No',
					),
				),
				array(
					'id' => 'spec_descrip',
					'type' => 'mediumwysiwyg',
					'name' => 'Special Needs description',
				),
				array(
					'id' => 'last_update',
					'type' => 'datetime',
					'name' => 'last_update',
				),
				array(
					'id' => 'entry_date',
					'type' => 'date',
					'name' => 'entry_date',
				),
				array(
					'id' => 'adopted_date',
					'type' => 'date',
					'name' => 'Adopted Date',
				),
				array(
					'id' => 'pending',
					'type' => 'number',
					'name' => 'pending',
				),
				array(
					'id' => 'vol_comments',
					'type' => 'wysiwyg',
					'name' => 'Volunteer Comments',
				),
				array(
					'id' => 'pet_origin',
					'type' => 'text',
					'name' => 'Pet Origin',
				),
				array(
					'id' => 'born_to',
					'type' => 'text',
					'name' => 'born_to',
				),
				array(
					'id' => 'offsite',
					'type' => 'text',
					'name' => 'offsite',
				),
				array(
					'id' => 'camp_ravenwood',
					'type' => 'number',
					'name' => 'camp_ravenwood',
				),
				array(
					'id' => 'adopted_date2',
					'type' => 'date',
					'name' => 'adopted_date2',
				),
				array(
					'id' => 'adopted_date3',
					'type' => 'date',
					'name' => 'adopted_date3',
				),
				array(
					'id' => 'pet_returned',
					'type' => 'date',
					'name' => 'pet_returned',
				),
				array(
					'id' => 'transfer_date',
					'type' => 'date',
					'name' => 'transfer_date',
				),
				array(
					'id' => 'at_office',
					'type' => 'number',
					'name' => 'at_office',
				),
				array(
					'id' => 'black_friday',
					'type' => 'number',
					'name' => 'black_friday',
				),
				array(
					'id' => 'origin_reason',
					'type' => 'wysiwyg',
					'name' => 'origin_reason',
				),
				array(
					'id' => 'pets_number',
					'type' => 'number',
					'name' => 'pets_number',
				),
				array(
					'id' => 'pet_DOD',
					'type' => 'date',
					'name' => 'pet_DOD',
				),
				array(
					'id' => 'video',
					'type' => 'video',
					'name' => 'video',
				),
				array(
					'id' => 'bissell',
					'type' => 'tinynumber',
					'name' => 'bissell',
				),
				array(
					'id' => 'cafe',
					'type' => 'tinynumber',
					'name' => 'cafe',
				),
				array(
					'id' => 'barn',
					'type' => 'tinynumber',
					'name' => 'barn',
				),
				array(
					'id' => 'ready_to_fix',
					'type' => 'tinynumber',
					'name' => 'ready_to_fix',
				),

			),
		);

		return $meta_boxes;
	}

	/**
	 * Attached to activate_{ plugin_basename( __FILES__ ) } by register_activation_hook()
	 * @static
	 */
	public static function plugin_activation() {
		return true;
	}

	/**
	 * Removes all connection options
	 * @static
	 */
	public static function plugin_deactivation() {
		return true;
	}
}
